version: '3.7'

services:

  vesuvius:
    container_name: vesuvius
    build:
      context: .
      dockerfile: Dockerfile
    command: [ 'sh', 'run_prod.sh' ]
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - /var/run/dbus/:/var/run/dbus/:z
    environment:
      - VESUVIUS_PORT=${VESUVIUS_EXTERNAL_PORT}
      - METRICS_PORT=${VESUVIUS_METRICS_PORT}
    stdin_open: true
    tty: true
